import { Product } from "./schema";

export const productsData: Product[] = [
  {
    id: "PRD001",
    name: "Black Forest Cake",
    category: "Cakes",
    description: "Classic chocolate cake with cherries, whipped cream, and chocolate shavings",
    price: 450,
    cost: 180,
    isAvailable: true,
    preparationTime: 120,
    popularity: 95,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD002",
    name: "Chocolate Truffle Cake",
    category: "Cakes",
    description: "Rich chocolate cake layered with chocolate ganache and truffle frosting",
    price: 550,
    cost: 220,
    isAvailable: true,
    preparationTime: 150,
    popularity: 92,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD003",
    name: "Red Velvet Cake",
    category: "Cakes",
    description: "Velvety red cake with cream cheese frosting and vanilla flavor",
    price: 500,
    cost: 200,
    isAvailable: true,
    preparationTime: 130,
    popularity: 88,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD004",
    name: "Vanilla Sponge Cake",
    category: "Cakes",
    description: "Light and fluffy vanilla sponge cake with buttercream frosting",
    price: 350,
    cost: 140,
    isAvailable: true,
    preparationTime: 90,
    popularity: 85,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD005",
    name: "Strawberry Shortcake",
    category: "Cakes",
    description: "Fresh strawberries layered with whipped cream and sponge cake",
    price: 400,
    cost: 160,
    isAvailable: true,
    preparationTime: 100,
    popularity: 90,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD006",
    name: "Chocolate Eclair",
    category: "Pastries",
    description: "Cream-filled choux pastry topped with rich chocolate glaze",
    price: 45,
    cost: 18,
    isAvailable: true,
    preparationTime: 60,
    popularity: 94,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD007",
    name: "Croissant",
    category: "Pastries",
    description: "Buttery, flaky French pastry with golden layers",
    price: 35,
    cost: 14,
    isAvailable: true,
    preparationTime: 180,
    popularity: 87,
    allergens: ["Dairy", "Gluten"],
  },
  {
    id: "PRD008",
    name: "Blueberry Muffin",
    category: "Muffins",
    description: "Soft muffin loaded with fresh blueberries and topped with streusel",
    price: 40,
    cost: 16,
    isAvailable: true,
    preparationTime: 30,
    popularity: 82,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD009",
    name: "Chocolate Chip Cookie",
    category: "Cookies",
    description: "Classic cookie with premium chocolate chips, crispy edges and chewy center",
    price: 25,
    cost: 10,
    isAvailable: true,
    preparationTime: 20,
    popularity: 96,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD010",
    name: "White Bread Loaf",
    category: "Bread",
    description: "Freshly baked soft white bread, perfect for sandwiches",
    price: 60,
    cost: 24,
    isAvailable: true,
    preparationTime: 240,
    popularity: 80,
    allergens: ["Gluten"],
  },
  {
    id: "PRD011",
    name: "Whole Wheat Bread",
    category: "Bread",
    description: "Healthy whole grain bread with nutty flavor and soft texture",
    price: 70,
    cost: 28,
    isAvailable: true,
    preparationTime: 240,
    popularity: 75,
    allergens: ["Gluten"],
  },
  {
    id: "PRD012",
    name: "Danish Pastry",
    category: "Pastries",
    description: "Buttery pastry with fruit filling and sweet glaze",
    price: 50,
    cost: 20,
    isAvailable: true,
    preparationTime: 90,
    popularity: 78,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD013",
    name: "Cinnamon Roll",
    category: "Pastries",
    description: "Swirled sweet bread with cinnamon sugar and cream cheese frosting",
    price: 55,
    cost: 22,
    isAvailable: true,
    preparationTime: 120,
    popularity: 89,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD014",
    name: "Tiramisu",
    category: "Desserts",
    description: "Italian dessert with coffee-soaked ladyfingers and mascarpone cream",
    price: 120,
    cost: 48,
    isAvailable: false,
    preparationTime: 180,
    popularity: 91,
    allergens: ["Dairy", "Eggs", "Gluten"],
  },
  {
    id: "PRD015",
    name: "Macarons (Box of 6)",
    category: "Pastries",
    description: "Delicate French macarons in assorted flavors with ganache filling",
    price: 300,
    cost: 120,
    isAvailable: true,
    preparationTime: 150,
    popularity: 93,
    allergens: ["Dairy", "Eggs", "Nuts"],
  },
];


