import { Product } from "./schema";

export const productsData: Product[] = [
  {
    id: "PRD001",
    name: "Butter Chicken",
    category: "Curries",
    description: "Tender chicken in rich tomato and cream sauce with aromatic spices",
    price: 299,
    cost: 120,
    isAvailable: true,
    preparationTime: 25,
    popularity: 95,
    allergens: ["Dairy"],
  },
  {
    id: "PRD002",
    name: "Dal Tadka",
    category: "Dal",
    description: "Yellow lentils tempered with cumin, garlic, and aromatic spices",
    price: 199,
    cost: 60,
    isAvailable: true,
    preparationTime: 15,
    popularity: 88,
    allergens: [],
  },
  {
    id: "PRD003",
    name: "Fish Curry",
    category: "Seafood",
    description: "Fresh fish cooked in coconut milk with Kerala spices",
    price: 399,
    cost: 180,
    isAvailable: true,
    preparationTime: 30,
    popularity: 92,
    allergens: ["Fish"],
  },
  {
    id: "PRD004",
    name: "Paneer Tikka",
    category: "Appetizers",
    description: "Grilled cottage cheese marinated in yogurt and spices",
    price: 249,
    cost: 100,
    isAvailable: true,
    preparationTime: 20,
    popularity: 90,
    allergens: ["Dairy"],
  },
  {
    id: "PRD005",
    name: "Chicken Biryani",
    category: "Rice",
    description: "Fragrant basmati rice with spiced chicken and saffron",
    price: 349,
    cost: 150,
    isAvailable: true,
    preparationTime: 35,
    popularity: 85,
    allergens: [],
  },
  {
    id: "PRD006",
    name: "Mutton Rogan Josh",
    category: "Curries",
    description: "Slow-cooked mutton in rich onion and tomato gravy",
    price: 499,
    cost: 250,
    isAvailable: false,
    preparationTime: 45,
    popularity: 78,
    allergens: [],
  },
  {
    id: "PRD007",
    name: "Aloo Gobi",
    category: "Vegetables",
    description: "Potatoes and cauliflower cooked with Indian spices",
    price: 179,
    cost: 70,
    isAvailable: true,
    preparationTime: 20,
    popularity: 76,
    allergens: [],
  },
  {
    id: "PRD008",
    name: "Fish Fry",
    category: "Seafood",
    description: "Crispy fried fish with Kerala spices and curry leaves",
    price: 329,
    cost: 150,
    isAvailable: true,
    preparationTime: 25,
    popularity: 82,
    allergens: ["Fish"],
  },
  {
    id: "PRD009",
    name: "Gulab Jamun",
    category: "Desserts",
    description: "Soft milk dumplings in rose-flavored sugar syrup",
    price: 149,
    cost: 50,
    isAvailable: true,
    preparationTime: 15,
    popularity: 94,
    allergens: ["Dairy"],
  },
  {
    id: "PRD010",
    name: "Raita",
    category: "Sides",
    description: "Fresh yogurt with cucumber, mint, and spices",
    price: 99,
    cost: 30,
    isAvailable: true,
    preparationTime: 5,
    popularity: 80,
    allergens: ["Dairy"],
  },
  {
    id: "PRD011",
    name: "Tandoori Chicken",
    category: "Grilled",
    description: "Marinated chicken cooked in clay oven with spices",
    price: 379,
    cost: 160,
    isAvailable: true,
    preparationTime: 30,
    popularity: 89,
    allergens: [],
  },
  {
    id: "PRD012",
    name: "Rajma Masala",
    category: "Curries",
    description: "Red kidney beans in rich onion and tomato gravy",
    price: 229,
    cost: 80,
    isAvailable: true,
    preparationTime: 25,
    popularity: 73,
    allergens: [],
  },
  {
    id: "PRD013",
    name: "Samosa",
    category: "Appetizers",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 49,
    cost: 15,
    isAvailable: true,
    preparationTime: 10,
    popularity: 77,
    allergens: ["Gluten"],
  },
  {
    id: "PRD014",
    name: "Prawn Curry",
    category: "Seafood",
    description: "Fresh prawns cooked in coconut milk with curry leaves",
    price: 449,
    cost: 200,
    isAvailable: false,
    preparationTime: 20,
    popularity: 65,
    allergens: ["Shellfish"],
  },
  {
    id: "PRD015",
    name: "Kheer",
    category: "Desserts",
    description: "Traditional rice pudding with cardamom and nuts",
    price: 129,
    cost: 40,
    isAvailable: true,
    preparationTime: 5,
    popularity: 91,
    allergens: ["Gluten", "Dairy", "Eggs"],
  },
];


