import { Product } from "./schema";

export const productsData: Product[] = [
  {
    id: "PRD001",
    name: "Classic Burger",
    category: "Burgers",
    description: "Juicy beef patty with lettuce, tomato, and special sauce",
    price: 12.99,
    cost: 4.50,
    isAvailable: true,
    preparationTime: 15,
    popularity: 95,
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "PRD002",
    name: "Caesar Salad",
    category: "Salads",
    description: "Fresh romaine lettuce with parmesan and Caesar dressing",
    price: 9.99,
    cost: 3.20,
    isAvailable: true,
    preparationTime: 8,
    popularity: 88,
    allergens: ["Dairy", "Eggs"],
  },
  {
    id: "PRD003",
    name: "Grilled Salmon",
    category: "Seafood",
    description: "Atlantic salmon with lemon butter and seasonal vegetables",
    price: 24.99,
    cost: 12.00,
    isAvailable: true,
    preparationTime: 20,
    popularity: 92,
    allergens: ["Fish"],
  },
  {
    id: "PRD004",
    name: "Margherita Pizza",
    category: "Pizza",
    description: "Classic pizza with tomato, mozzarella, and fresh basil",
    price: 14.99,
    cost: 4.80,
    isAvailable: true,
    preparationTime: 18,
    popularity: 90,
    allergens: ["Gluten", "Dairy"],
  },
  {
    id: "PRD005",
    name: "Chicken Wings",
    category: "Appetizers",
    description: "Crispy wings with choice of sauce",
    price: 11.99,
    cost: 4.20,
    isAvailable: true,
    preparationTime: 12,
    popularity: 85,
    allergens: ["Gluten"],
  },
  {
    id: "PRD006",
    name: "Ribeye Steak",
    category: "Steaks",
    description: "16oz premium ribeye cooked to perfection",
    price: 32.99,
    cost: 15.50,
    isAvailable: false,
    preparationTime: 25,
    popularity: 78,
    allergens: [],
  },
  {
    id: "PRD007",
    name: "Vegetarian Pasta",
    category: "Pasta",
    description: "Penne with seasonal vegetables in olive oil and garlic",
    price: 13.99,
    cost: 4.00,
    isAvailable: true,
    preparationTime: 15,
    popularity: 76,
    allergens: ["Gluten"],
  },
  {
    id: "PRD008",
    name: "Fish & Chips",
    category: "Seafood",
    description: "Beer-battered cod with crispy fries and tartar sauce",
    price: 16.99,
    cost: 6.50,
    isAvailable: true,
    preparationTime: 18,
    popularity: 82,
    allergens: ["Fish", "Gluten"],
  },
  {
    id: "PRD009",
    name: "Chocolate Lava Cake",
    category: "Desserts",
    description: "Warm chocolate cake with molten center and vanilla ice cream",
    price: 8.99,
    cost: 2.80,
    isAvailable: true,
    preparationTime: 10,
    popularity: 94,
    allergens: ["Gluten", "Dairy", "Eggs"],
  },
  {
    id: "PRD010",
    name: "Greek Salad",
    category: "Salads",
    description: "Mixed greens with feta, olives, and Greek dressing",
    price: 10.99,
    cost: 3.50,
    isAvailable: true,
    preparationTime: 8,
    popularity: 80,
    allergens: ["Dairy"],
  },
  {
    id: "PRD011",
    name: "BBQ Ribs",
    category: "BBQ",
    description: "Slow-cooked pork ribs with house BBQ sauce",
    price: 22.99,
    cost: 9.00,
    isAvailable: true,
    preparationTime: 30,
    popularity: 89,
    allergens: ["Gluten"],
  },
  {
    id: "PRD012",
    name: "Mushroom Risotto",
    category: "Pasta",
    description: "Creamy arborio rice with wild mushrooms and parmesan",
    price: 16.99,
    cost: 5.20,
    isAvailable: true,
    preparationTime: 22,
    popularity: 73,
    allergens: ["Dairy"],
  },
  {
    id: "PRD013",
    name: "Caprese Salad",
    category: "Salads",
    description: "Fresh mozzarella, tomatoes, and basil with balsamic glaze",
    price: 11.99,
    cost: 4.00,
    isAvailable: true,
    preparationTime: 5,
    popularity: 77,
    allergens: ["Dairy"],
  },
  {
    id: "PRD014",
    name: "Lobster Thermidor",
    category: "Seafood",
    description: "Fresh lobster in creamy brandy sauce",
    price: 42.99,
    cost: 22.00,
    isAvailable: false,
    preparationTime: 35,
    popularity: 65,
    allergens: ["Shellfish", "Dairy"],
  },
  {
    id: "PRD015",
    name: "Tiramisu",
    category: "Desserts",
    description: "Classic Italian dessert with coffee and mascarpone",
    price: 7.99,
    cost: 2.50,
    isAvailable: true,
    preparationTime: 5,
    popularity: 91,
    allergens: ["Gluten", "Dairy", "Eggs"],
  },
];


