import { InventoryItem } from "./schema";

export const inventoryData: InventoryItem[] = [
  {
    id: "INV001",
    itemName: "Chicken Breast",
    category: "Meat & Poultry",
    quantity: 45,
    unit: "kg",
    reorderLevel: 20,
    costPerUnit: 8.50,
    supplier: "Fresh Farms Co.",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV002",
    itemName: "Tomatoes",
    category: "Vegetables",
    quantity: 12,
    unit: "kg",
    reorderLevel: 15,
    costPerUnit: 3.20,
    supplier: "Garden Fresh Supplies",
    lastRestocked: "2024-10-20",
    status: "Low Stock",
  },
  {
    id: "INV003",
    itemName: "Olive Oil",
    category: "Oils & Condiments",
    quantity: 25,
    unit: "liters",
    reorderLevel: 10,
    costPerUnit: 12.00,
    supplier: "Mediterranean Imports",
    lastRestocked: "2024-10-18",
    status: "In Stock",
  },
  {
    id: "INV004",
    itemName: "Flour",
    category: "Dry Goods",
    quantity: 8,
    unit: "kg",
    reorderLevel: 25,
    costPerUnit: 2.50,
    supplier: "Bakery Essentials Ltd.",
    lastRestocked: "2024-10-15",
    status: "Low Stock",
  },
  {
    id: "INV005",
    itemName: "Fresh Salmon",
    category: "Seafood",
    quantity: 18,
    unit: "kg",
    reorderLevel: 10,
    costPerUnit: 22.00,
    supplier: "Ocean Catch Suppliers",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV006",
    itemName: "Mozzarella Cheese",
    category: "Dairy",
    quantity: 0,
    unit: "kg",
    reorderLevel: 15,
    costPerUnit: 9.75,
    supplier: "Dairy Delights Inc.",
    lastRestocked: "2024-10-10",
    status: "Out of Stock",
  },
  {
    id: "INV007",
    itemName: "Lettuce",
    category: "Vegetables",
    quantity: 30,
    unit: "heads",
    reorderLevel: 20,
    costPerUnit: 1.50,
    supplier: "Garden Fresh Supplies",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV008",
    itemName: "Ground Beef",
    category: "Meat & Poultry",
    quantity: 35,
    unit: "kg",
    reorderLevel: 20,
    costPerUnit: 10.00,
    supplier: "Fresh Farms Co.",
    lastRestocked: "2024-10-22",
    status: "In Stock",
  },
  {
    id: "INV009",
    itemName: "Pasta",
    category: "Dry Goods",
    quantity: 50,
    unit: "kg",
    reorderLevel: 30,
    costPerUnit: 3.00,
    supplier: "Italian Imports",
    lastRestocked: "2024-10-20",
    status: "In Stock",
  },
  {
    id: "INV010",
    itemName: "Garlic",
    category: "Vegetables",
    quantity: 5,
    unit: "kg",
    reorderLevel: 8,
    costPerUnit: 4.50,
    supplier: "Garden Fresh Supplies",
    lastRestocked: "2024-10-18",
    status: "Low Stock",
  },
  {
    id: "INV011",
    itemName: "Heavy Cream",
    category: "Dairy",
    quantity: 20,
    unit: "liters",
    reorderLevel: 12,
    costPerUnit: 5.25,
    supplier: "Dairy Delights Inc.",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV012",
    itemName: "Red Wine",
    category: "Beverages",
    quantity: 42,
    unit: "bottles",
    reorderLevel: 30,
    costPerUnit: 15.00,
    supplier: "Wine Cellar Distributors",
    lastRestocked: "2024-10-21",
    status: "In Stock",
  },
  {
    id: "INV013",
    itemName: "Butter",
    category: "Dairy",
    quantity: 10,
    unit: "kg",
    reorderLevel: 15,
    costPerUnit: 7.50,
    supplier: "Dairy Delights Inc.",
    lastRestocked: "2024-10-19",
    status: "Low Stock",
  },
  {
    id: "INV014",
    itemName: "Shrimp",
    category: "Seafood",
    quantity: 25,
    unit: "kg",
    reorderLevel: 12,
    costPerUnit: 18.50,
    supplier: "Ocean Catch Suppliers",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV015",
    itemName: "Balsamic Vinegar",
    category: "Oils & Condiments",
    quantity: 15,
    unit: "liters",
    reorderLevel: 8,
    costPerUnit: 8.00,
    supplier: "Mediterranean Imports",
    lastRestocked: "2024-10-22",
    status: "In Stock",
  },
];


