import { InventoryItem } from "./schema";

export const inventoryData: InventoryItem[] = [
  {
    id: "INV001",
    itemName: "Chicken Breast",
    category: "Meat & Poultry",
    quantity: 45,
    unit: "kg",
    reorderLevel: 20,
    costPerUnit: 320,
    supplier: "Rajesh Poultry Farm",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV002",
    itemName: "Tomatoes",
    category: "Vegetables",
    quantity: 12,
    unit: "kg",
    reorderLevel: 15,
    costPerUnit: 120,
    supplier: "Green Valley Vegetables",
    lastRestocked: "2024-10-20",
    status: "Low Stock",
  },
  {
    id: "INV003",
    itemName: "Mustard Oil",
    category: "Oils & Ghee",
    quantity: 25,
    unit: "liters",
    reorderLevel: 10,
    costPerUnit: 450,
    supplier: "Spice King Traders",
    lastRestocked: "2024-10-18",
    status: "In Stock",
  },
  {
    id: "INV004",
    itemName: "Basmati Rice",
    category: "Grains & Pulses",
    quantity: 8,
    unit: "kg",
    reorderLevel: 25,
    costPerUnit: 95,
    supplier: "Basmati Rice Suppliers",
    lastRestocked: "2024-10-15",
    status: "Low Stock",
  },
  {
    id: "INV005",
    itemName: "Fresh Fish",
    category: "Seafood",
    quantity: 18,
    unit: "kg",
    reorderLevel: 10,
    costPerUnit: 850,
    supplier: "Coastal Fish Suppliers",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV006",
    itemName: "Paneer",
    category: "Dairy Products",
    quantity: 0,
    unit: "kg",
    reorderLevel: 15,
    costPerUnit: 380,
    supplier: "Amul Dairy Products",
    lastRestocked: "2024-10-10",
    status: "Out of Stock",
  },
  {
    id: "INV007",
    itemName: "Onions",
    category: "Vegetables",
    quantity: 30,
    unit: "kg",
    reorderLevel: 20,
    costPerUnit: 60,
    supplier: "Green Valley Vegetables",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV008",
    itemName: "Mutton",
    category: "Meat & Poultry",
    quantity: 35,
    unit: "kg",
    reorderLevel: 20,
    costPerUnit: 650,
    supplier: "Premium Meat Suppliers",
    lastRestocked: "2024-10-22",
    status: "In Stock",
  },
  {
    id: "INV009",
    itemName: "Wheat Flour",
    category: "Grains & Pulses",
    quantity: 50,
    unit: "kg",
    reorderLevel: 30,
    costPerUnit: 45,
    supplier: "Golden Grain Mills",
    lastRestocked: "2024-10-20",
    status: "In Stock",
  },
  {
    id: "INV010",
    itemName: "Garlic",
    category: "Vegetables",
    quantity: 5,
    unit: "kg",
    reorderLevel: 8,
    costPerUnit: 180,
    supplier: "Green Valley Vegetables",
    lastRestocked: "2024-10-18",
    status: "Low Stock",
  },
  {
    id: "INV011",
    itemName: "Yogurt",
    category: "Dairy Products",
    quantity: 20,
    unit: "liters",
    reorderLevel: 12,
    costPerUnit: 200,
    supplier: "Amul Dairy Products",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV012",
    itemName: "Tea Leaves",
    category: "Beverages",
    quantity: 42,
    unit: "kg",
    reorderLevel: 30,
    costPerUnit: 600,
    supplier: "Royal Tea Traders",
    lastRestocked: "2024-10-21",
    status: "In Stock",
  },
  {
    id: "INV013",
    itemName: "Ghee",
    category: "Dairy Products",
    quantity: 10,
    unit: "kg",
    reorderLevel: 15,
    costPerUnit: 300,
    supplier: "Amul Dairy Products",
    lastRestocked: "2024-10-19",
    status: "Low Stock",
  },
  {
    id: "INV014",
    itemName: "Prawns",
    category: "Seafood",
    quantity: 25,
    unit: "kg",
    reorderLevel: 12,
    costPerUnit: 750,
    supplier: "Coastal Fish Suppliers",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV015",
    itemName: "Turmeric Powder",
    category: "Spices & Masalas",
    quantity: 15,
    unit: "kg",
    reorderLevel: 8,
    costPerUnit: 320,
    supplier: "Masala Magic Traders",
    lastRestocked: "2024-10-22",
    status: "In Stock",
  },
];


