import { InventoryItem } from "./schema";

export const inventoryData: InventoryItem[] = [
  {
    id: "INV001",
    itemName: "Wheat Flour",
    category: "Raw Materials",
    quantity: 150,
    unit: "kg",
    reorderLevel: 50,
    costPerUnit: 45,
    supplier: "Golden Grain Mills",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV002",
    itemName: "All-Purpose Flour",
    category: "Raw Materials",
    quantity: 80,
    unit: "kg",
    reorderLevel: 30,
    costPerUnit: 50,
    supplier: "Golden Grain Mills",
    lastRestocked: "2024-10-22",
    status: "In Stock",
  },
  {
    id: "INV003",
    itemName: "Sugar",
    category: "Raw Materials",
    quantity: 120,
    unit: "kg",
    reorderLevel: 40,
    costPerUnit: 42,
    supplier: "Sweet Sugar Traders",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV004",
    itemName: "Butter",
    category: "Dairy Products",
    quantity: 45,
    unit: "kg",
    reorderLevel: 20,
    costPerUnit: 520,
    supplier: "Amul Dairy Products",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV005",
    itemName: "Eggs",
    category: "Dairy Products",
    quantity: 500,
    unit: "pieces",
    reorderLevel: 200,
    costPerUnit: 8,
    supplier: "Fresh Farm Eggs",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV006",
    itemName: "Milk",
    category: "Dairy Products",
    quantity: 0,
    unit: "liters",
    reorderLevel: 50,
    costPerUnit: 60,
    supplier: "Amul Dairy Products",
    lastRestocked: "2024-10-20",
    status: "Out of Stock",
  },
  {
    id: "INV007",
    itemName: "Yeast",
    category: "Raw Materials",
    quantity: 8,
    unit: "kg",
    reorderLevel: 5,
    costPerUnit: 280,
    supplier: "Baking Essentials Co.",
    lastRestocked: "2024-10-21",
    status: "In Stock",
  },
  {
    id: "INV008",
    itemName: "Baking Powder",
    category: "Raw Materials",
    quantity: 12,
    unit: "kg",
    reorderLevel: 8,
    costPerUnit: 320,
    supplier: "Baking Essentials Co.",
    lastRestocked: "2024-10-22",
    status: "In Stock",
  },
  {
    id: "INV009",
    itemName: "Potatoes",
    category: "Vegetables",
    quantity: 200,
    unit: "kg",
    reorderLevel: 100,
    costPerUnit: 25,
    supplier: "Fresh Vegetables Market",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV010",
    itemName: "Green Chilies",
    category: "Vegetables",
    quantity: 15,
    unit: "kg",
    reorderLevel: 10,
    costPerUnit: 120,
    supplier: "Fresh Vegetables Market",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV011",
    itemName: "Garlic",
    category: "Vegetables",
    quantity: 25,
    unit: "kg",
    reorderLevel: 15,
    costPerUnit: 180,
    supplier: "Fresh Vegetables Market",
    lastRestocked: "2024-10-22",
    status: "In Stock",
  },
  {
    id: "INV012",
    itemName: "Ginger",
    category: "Vegetables",
    quantity: 18,
    unit: "kg",
    reorderLevel: 10,
    costPerUnit: 200,
    supplier: "Fresh Vegetables Market",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV013",
    itemName: "Turmeric Powder",
    category: "Spices & Condiments",
    quantity: 20,
    unit: "kg",
    reorderLevel: 10,
    costPerUnit: 320,
    supplier: "Spice King Traders",
    lastRestocked: "2024-10-21",
    status: "In Stock",
  },
  {
    id: "INV014",
    itemName: "Mustard Seeds",
    category: "Spices & Condiments",
    quantity: 12,
    unit: "kg",
    reorderLevel: 8,
    costPerUnit: 280,
    supplier: "Spice King Traders",
    lastRestocked: "2024-10-20",
    status: "In Stock",
  },
  {
    id: "INV015",
    itemName: "Curry Leaves",
    category: "Vegetables",
    quantity: 5,
    unit: "kg",
    reorderLevel: 3,
    costPerUnit: 400,
    supplier: "Fresh Vegetables Market",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV016",
    itemName: "Cooking Oil",
    category: "Raw Materials",
    quantity: 80,
    unit: "liters",
    reorderLevel: 40,
    costPerUnit: 120,
    supplier: "Oil & Ghee Suppliers",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV017",
    itemName: "Vanilla Extract",
    category: "Raw Materials",
    quantity: 8,
    unit: "liters",
    reorderLevel: 5,
    costPerUnit: 850,
    supplier: "Baking Essentials Co.",
    lastRestocked: "2024-10-19",
    status: "Low Stock",
  },
  {
    id: "INV018",
    itemName: "Chocolate Chips",
    category: "Raw Materials",
    quantity: 25,
    unit: "kg",
    reorderLevel: 15,
    costPerUnit: 650,
    supplier: "Sweet Treats Suppliers",
    lastRestocked: "2024-10-22",
    status: "In Stock",
  },
  {
    id: "INV019",
    itemName: "Cocoa Powder",
    category: "Raw Materials",
    quantity: 15,
    unit: "kg",
    reorderLevel: 10,
    costPerUnit: 580,
    supplier: "Sweet Treats Suppliers",
    lastRestocked: "2024-10-21",
    status: "In Stock",
  },
  {
    id: "INV020",
    itemName: "Pav Bread",
    category: "Bakery Products",
    quantity: 500,
    unit: "pieces",
    reorderLevel: 200,
    costPerUnit: 3,
    supplier: "Fresh Bakery Supplies",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV021",
    itemName: "Vada Pav Patties",
    category: "Bakery Products",
    quantity: 300,
    unit: "pieces",
    reorderLevel: 150,
    costPerUnit: 5,
    supplier: "In-House Production",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV022",
    itemName: "Samosa",
    category: "Bakery Products",
    quantity: 250,
    unit: "pieces",
    reorderLevel: 100,
    costPerUnit: 4,
    supplier: "In-House Production",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV023",
    itemName: "Black Forest Cake",
    category: "Bakery Products",
    quantity: 12,
    unit: "pieces",
    reorderLevel: 5,
    costPerUnit: 180,
    supplier: "In-House Production",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV024",
    itemName: "Chocolate Cake",
    category: "Bakery Products",
    quantity: 8,
    unit: "pieces",
    reorderLevel: 5,
    costPerUnit: 220,
    supplier: "In-House Production",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV025",
    itemName: "White Bread",
    category: "Bakery Products",
    quantity: 60,
    unit: "loaves",
    reorderLevel: 30,
    costPerUnit: 24,
    supplier: "In-House Production",
    lastRestocked: "2024-10-24",
    status: "In Stock",
  },
  {
    id: "INV026",
    itemName: "Cream",
    category: "Dairy Products",
    quantity: 30,
    unit: "liters",
    reorderLevel: 15,
    costPerUnit: 180,
    supplier: "Amul Dairy Products",
    lastRestocked: "2024-10-23",
    status: "In Stock",
  },
  {
    id: "INV027",
    itemName: "Salt",
    category: "Spices & Condiments",
    quantity: 50,
    unit: "kg",
    reorderLevel: 25,
    costPerUnit: 15,
    supplier: "Spice King Traders",
    lastRestocked: "2024-10-20",
    status: "In Stock",
  },
  {
    id: "INV028",
    itemName: "Cumin Seeds",
    category: "Spices & Condiments",
    quantity: 10,
    unit: "kg",
    reorderLevel: 5,
    costPerUnit: 350,
    supplier: "Spice King Traders",
    lastRestocked: "2024-10-19",
    status: "Low Stock",
  },
];
