import { Supplier } from "./schema";

export const suppliersData: Supplier[] = [
  {
    id: "SUP001",
    name: "Fresh Farms Co.",
    category: "Meat & Poultry",
    contactPerson: "John Miller",
    email: "john@freshfarms.com",
    phone: "(555) 123-4567",
    address: "123 Farm Road, Agriculture Valley, CA 90210",
    rating: 4.8,
    totalOrders: 247,
    lastOrderDate: "2024-10-23",
    status: "Active",
  },
  {
    id: "SUP002",
    name: "Garden Fresh Supplies",
    category: "Vegetables",
    contactPerson: "Sarah Green",
    email: "sarah@gardenfresh.com",
    phone: "(555) 234-5678",
    address: "456 Garden Lane, Green Hills, CA 90211",
    rating: 4.6,
    totalOrders: 189,
    lastOrderDate: "2024-10-24",
    status: "Active",
  },
  {
    id: "SUP003",
    name: "Ocean Catch Suppliers",
    category: "Seafood",
    contactPerson: "Mike Waters",
    email: "mike@oceancatch.com",
    phone: "(555) 345-6789",
    address: "789 Harbor Drive, Coastal City, CA 90212",
    rating: 4.9,
    totalOrders: 156,
    lastOrderDate: "2024-10-24",
    status: "Active",
  },
  {
    id: "SUP004",
    name: "Dairy Delights Inc.",
    category: "Dairy Products",
    contactPerson: "Emily Cheese",
    email: "emily@dairydelights.com",
    phone: "(555) 456-7890",
    address: "321 Dairy Road, Milk Valley, CA 90213",
    rating: 4.7,
    totalOrders: 203,
    lastOrderDate: "2024-10-22",
    status: "Active",
  },
  {
    id: "SUP005",
    name: "Mediterranean Imports",
    category: "Oils & Condiments",
    contactPerson: "Antonio Olive",
    email: "antonio@medimports.com",
    phone: "(555) 567-8901",
    address: "654 Trade Street, Import City, CA 90214",
    rating: 4.5,
    totalOrders: 98,
    lastOrderDate: "2024-10-21",
    status: "Active",
  },
  {
    id: "SUP006",
    name: "Bakery Essentials Ltd.",
    category: "Dry Goods",
    contactPerson: "Lisa Baker",
    email: "lisa@bakeryessentials.com",
    phone: "(555) 678-9012",
    address: "987 Flour Mill Road, Baker Town, CA 90215",
    rating: 4.4,
    totalOrders: 134,
    lastOrderDate: "2024-10-18",
    status: "Active",
  },
  {
    id: "SUP007",
    name: "Wine Cellar Distributors",
    category: "Beverages",
    contactPerson: "Vincent Grape",
    email: "vincent@winecellar.com",
    phone: "(555) 789-0123",
    address: "147 Vineyard Ave, Wine Country, CA 90216",
    rating: 4.8,
    totalOrders: 87,
    lastOrderDate: "2024-10-20",
    status: "Active",
  },
  {
    id: "SUP008",
    name: "Italian Imports",
    category: "Dry Goods",
    contactPerson: "Marco Rossi",
    email: "marco@italianmports.com",
    phone: "(555) 890-1234",
    address: "258 Italy Street, Little Rome, CA 90217",
    rating: 4.6,
    totalOrders: 112,
    lastOrderDate: "2024-10-19",
    status: "Active",
  },
  {
    id: "SUP009",
    name: "Spice World Traders",
    category: "Spices & Herbs",
    contactPerson: "Raj Patel",
    email: "raj@spiceworld.com",
    phone: "(555) 901-2345",
    address: "369 Spice Route, Flavor Town, CA 90218",
    rating: 4.7,
    totalOrders: 145,
    lastOrderDate: "2024-10-15",
    status: "On Hold",
  },
  {
    id: "SUP010",
    name: "Organic Harvest",
    category: "Vegetables",
    contactPerson: "Emma Natural",
    email: "emma@organicharvest.com",
    phone: "(555) 012-3456",
    address: "741 Organic Farm Road, Green Valley, CA 90219",
    rating: 4.9,
    totalOrders: 178,
    lastOrderDate: "2024-10-23",
    status: "Active",
  },
  {
    id: "SUP011",
    name: "Premium Cuts Wholesale",
    category: "Meat & Poultry",
    contactPerson: "Robert Steak",
    email: "robert@premiumcuts.com",
    phone: "(555) 123-4560",
    address: "852 Butcher Lane, Meat District, CA 90220",
    rating: 4.5,
    totalOrders: 96,
    lastOrderDate: "2024-10-10",
    status: "Inactive",
  },
  {
    id: "SUP012",
    name: "Global Coffee Traders",
    category: "Beverages",
    contactPerson: "Carlos Bean",
    email: "carlos@globalcoffee.com",
    phone: "(555) 234-5601",
    address: "963 Coffee Avenue, Bean City, CA 90221",
    rating: 4.8,
    totalOrders: 167,
    lastOrderDate: "2024-10-22",
    status: "Active",
  },
];


